/// The identity of a person, as the provider currently describes them.
///
/// This is a snapshot: [groups] in particular is re-read on every
/// revalidation, because losing group membership has to revoke access just
/// like disabling the account does.
class AuthenticatedUser {
  /// Stable provider-side identifier (the OIDC `sub` claim). Used as the
  /// primary key — unlike an email address it does not change.
  final String id;

  final String email;
  final String displayName;
  final List<String> groups;

  const AuthenticatedUser({
    required this.id,
    required this.email,
    required this.displayName,
    this.groups = const [],
  });

  @override
  String toString() => 'AuthenticatedUser($id, $email)';
}

/// Tokens as returned by the provider's token endpoint.
class OidcTokens {
  final String accessToken;

  /// Only present when `offline_access` was granted. Without it a user can
  /// never be re-checked, so the auth layer refuses to create a session.
  final String? refreshToken;

  final String? idToken;
  final DateTime? accessTokenExpiresAt;

  const OidcTokens({
    required this.accessToken,
    this.refreshToken,
    this.idToken,
    this.accessTokenExpiresAt,
  });
}

/// Raised when the provider positively says a grant is no longer good —
/// `invalid_grant` from the token endpoint, or a 401/403 from userinfo.
///
/// Deliberately distinct from a transport failure: this one revokes access,
/// a network error must not.
class IdentityRevokedException implements Exception {
  final String message;
  IdentityRevokedException(this.message);
  @override
  String toString() => 'IdentityRevokedException: $message';
}

/// Raised when the provider could not be reached or answered with a server
/// error. Callers retry rather than revoke.
class IdentityUnavailableException implements Exception {
  final String message;
  IdentityUnavailableException(this.message);
  @override
  String toString() => 'IdentityUnavailableException: $message';
}

/// The parts of an OpenID Connect provider the auth layer depends on.
///
/// Kept as an interface so the revalidation strategy can be swapped without
/// touching the session machinery — e.g. for a provider that needs an
/// out-of-band admin API call to report disabled accounts.
abstract class IdentityProvider {
  /// Where to send the browser to start a login. [state], [nonce] and
  /// [codeChallenge] are generated by the caller and checked on return.
  /// [forceConsent] asks the provider to prompt the user again even though
  /// they have already approved this client. Some providers — Google among
  /// them — issue a refresh token only on the first consent, and without one
  /// this server cannot re-check the account. Asking again is what recovers
  /// that; refusing the sign-in instead leaves no way back at all.
  Future<Uri> authorizationUrl({
    required String state,
    required String nonce,
    required String codeChallenge,
    bool forceConsent = false,
  });

  /// Exchanges an authorization code for tokens, verifying that the returned
  /// id token was issued for us and carries the expected [nonce].
  Future<OidcTokens> exchangeCode({
    required String code,
    required String codeVerifier,
    required String nonce,
  });

  /// Trades a refresh token for a fresh access token. Throws
  /// [IdentityRevokedException] on `invalid_grant`.
  Future<OidcTokens> refresh(String refreshToken);

  /// Reads the current profile. This is the step that actually notices a
  /// disabled or deleted account: such a user cannot authenticate at all, so
  /// this fails for them even if the refresh grant happened to succeed —
  /// whether a provider checks the account state when refreshing is up to
  /// the provider.
  Future<AuthenticatedUser> userInfo(String accessToken);

  /// Provider url that ends the session on their side, or null if the
  /// provider does not advertise one.
  Future<Uri?> endSessionUrl({String? idToken, Uri? postLogoutRedirect});
}
